# experiment parameters
experiment_parameters:
    function_name: ackley
    dim: 100
    num_steps: 25000
    num_mc: 100
    num_tests: 100
    random_seed: 0


# distribution parameters
distribution_parameters:

    # logistic distribution
    - logistic:
        sigma: 1.0e+0
        lr: 3.0e+0

    # normal distribution
    - normal:
        sigma: 3.0e+0
        lr: 3.0e+0

    # t distribution
    - t:
        sigma: 3.0e+0
        lr: 1.0e+1

    # uniform distribution
    - uniform:
        sigma: 1.0e+1
        lr: 3.0e+0
