# experiment parameters
experiment_parameters:
    function_name: sphere
    dim: 100
    num_steps: 10000
    num_mc: 1000
    num_tests: 100
    random_seed: 0


# distribution parameters
distribution_parameters:

    # normal distribution
    - normal:
        sigma: 1.0e-0
        lr: 1.0e-3

    # uniform distribution
    - uniform:
        sigma: 1.0e-0
        lr: 1.0e-3

    # logistic distribution
    - logistic:
        sigma: 1.0e-0
        lr: 1.0e-3

    # t distribution
    - t:
        sigma: 1.0e-0
        lr: 1.0e-3
