# experiment parameters
experiment_parameters:
    function_name: rosenbrock
    dim: 100
    num_steps: 1000
    num_mc: 1000
    num_tests: 3
    random_seed: 1


# distribution parameters
distribution_parameters:

    # logistic distribution
    - logistic:
        sigma: 1.0e-0
        lr: 1.0e-3

    # normal distribution
    - normal:
        sigma: 1.0e-0
        lr: 1.0e-3

    # t distribution
    - t:
        sigma: 1.0e-3
        lr: 1.0e-3

    # uniform distribution
    - uniform:
        sigma: 1.0e-0
        lr: 1.0e-3
