# experiment parameters
experiment_parameters:
    function_name: levy
    dim: 100
    num_steps: 3000
    num_mc: 1000
    num_tests: 100
    random_seed: 0


# distribution parameters
distribution_parameters:

    # logistic distribution
    - logistic:
        sigma: 3.0e-6
        lr: 3.0e-3

    # normal distribution
    - normal:
        sigma: 1.0e-3
        lr: 1.0e-1

    # t distribution
    - t:
        sigma: 3.0e-6
        lr: 3.0e-4

    # uniform distribution
    - uniform:
        sigma: 3.0e+0
        lr: 1.0e+1
