# experiment parameters
experiment_parameters:
    function_name: rosenbrock
    dim: 100
    num_steps: 1000
    num_mc: 1000
    num_tests: 100
    random_seed: 0


# distribution parameters
distribution_parameters:

    # logistic distribution
    - logistic:
        sigma: 3.0e-1
        lr: 3.0e-6

    # normal distribution
    - normal:
        sigma: 3.0e-1
        lr: 3.0e-5

    # t distribution
    - t:
        sigma: 1.0e-4
        lr: 3.0e-5

    # uniform distribution
    - uniform:
        sigma: 3.0e-4
        lr: 1.0e-4
