# experiment parameters
experiment_parameters:
    function_name: sphere
    dim: 100
    num_steps: 10000
    num_mc: 1000
    num_tests: 100
    random_seed: 0


# distribution parameters
distribution_parameters:

    # logistic distribution
    - logistic:
        sigma: 1.0e-2
        lr: 1.0e-0

    # normal distribution
    - normal:
        sigma: 1.0e-6
        lr: 1.0e-2

    # t distribution
    - t:
        sigma: 1.0e-2
        lr: 1.0e-0

    # truncated normal distribution
    - truncnorm:
        sigma: 1.0e-6
        lr: 1.0e-2

    # uniform distribution
    - uniform:
        sigma: 1.0e-6
        lr: 1.0e-2
